---
- name: Install and Start nginx //description // what we are going to do 
  hosts: all
  become: true


  tasks:  //tasks
   - name: Install nginx
     apt:
       name: nginx
       state: present
   - name: start nginx
     service:
       name: nginx
       state: started



